summary: không tìm thấy trang404
value:
  css:
    buttoncomponent:
      button:
        class: ''
        style: ''
      container:
        class: ''
        style: ''
    textcomponent:
      container:
        class: ''
        style: ''
      text:
        class: ''
        style: ''
  fullscreen: true
  grid:
    - '12':
        fixed: false
        fullHeight: false
        h: 18
        w: 12
        x: 0
        'y': 0
      '3':
        fixed: false
        fullHeight: false
        h: 8
        w: 2
        x: 0
        'y': 0
      id: a
      data:
        id: a
        type: containercomponent
        actions: []
        configuration: {}
        customCss:
          container:
            class: ''
            style: ''
        numberOfSubgrids: 1
  hiddenInlineScripts: []
  hideLegacyTopBar: true
  mobileViewOnSmallerScreens: false
  norefreshbar: false
  subgrids:
    a-0:
      - '12':
          fixed: false
          fullHeight: false
          h: 4
          w: 2
          x: 5
          'y': 6
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 1
          x: 4
          'y': 7
        id: b
        data:
          id: b
          type: textcomponent
          actions: []
          componentInput:
            type: templatev2
            connections: []
            eval: '404'
            fieldType: template
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: false
            style:
              type: static
              value: Body
            tooltip:
              type: static
              value: ''
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: ''
              style: 'font-size: 100px;'
          horizontalAlignment: center
          verticalAlignment: center
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 4
          x: 4
          'y': 10
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 1
          x: 0
          'y': 0
        id: c
        data:
          id: c
          type: textcomponent
          actions: []
          componentInput:
            type: templatev2
            connections: []
            eval: Trang hiện tại bạn đang tìm kiếm không có!
            fieldType: template
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: false
            style:
              type: static
              value: Body
            tooltip:
              type: static
              value: ''
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: ''
              style: ''
          horizontalAlignment: center
          verticalAlignment: center
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 2
          x: 5
          'y': 11
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 1
          x: 1
          'y': 0
        id: d
        data:
          id: d
          type: buttoncomponent
          actions: []
          componentInput:
            type: runnable
            fields: {}
            fieldType: any
          configuration:
            afterIcon:
              type: static
              value: ''
            beforeIcon:
              type: static
              value: ''
            color:
              type: static
              value: blue
            confirmationModal:
              type: oneOf
              configuration:
                confirmationModal:
                  description:
                    type: static
                    value: Are you sure?
                  confirmationText:
                    type: static
                    value: Confirm
                  title:
                    type: static
                    value: Title
                none: {}
              selected: none
            disabled:
              type: static
              value: false
            fillContainer:
              type: static
              value: false
            label:
              type: static
              value: Về lại Trang chủ
            onError:
              type: oneOf
              configuration:
                close:
                  id:
                    type: static
                    value: ''
                errorOverlay: {}
                gotoUrl:
                  newTab:
                    type: static
                    value: true
                  url:
                    type: static
                    value: ''
                open:
                  id:
                    type: static
                    value: ''
                sendErrorToast:
                  appendError:
                    type: static
                    value: true
                  message:
                    type: static
                    value: An error occured
                setTab:
                  setTab:
                    type: static
                    value: []
              selected: errorOverlay
            onSuccess:
              type: oneOf
              configuration:
                clearFiles:
                  id:
                    type: static
                    value: ''
                close:
                  id:
                    type: static
                    value: ''
                closeModal:
                  modalId:
                    type: static
                    value: ''
                gotoUrl:
                  newTab:
                    type: static
                    value: true
                  url:
                    type: static
                    value: 'https://app.windmill.dev/a/opensource/home'
                none: {}
                open:
                  id:
                    type: static
                    value: ''
                openModal:
                  modalId:
                    type: static
                    value: ''
                sendToast:
                  message:
                    type: static
                    value: ''
                setTab:
                  setTab:
                    type: static
                    value: []
              selected: gotoUrl
            size:
              type: static
              value: md
            triggerOnAppLoad:
              type: static
              value: false
          customCss:
            button:
              class: ''
              style: ''
            container:
              class: ''
              style: ''
          horizontalAlignment: center
          recomputeIds: []
          verticalAlignment: center
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  execution_mode: anonymous
  s3_inputs: []
  triggerables_v2: {}
