FROM python:3.9-slim

# Thiết lập thư mục làm việc
WORKDIR /app

# Sao chép file requirements
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Sao chép toàn bộ code
COPY . /app

# Mở port
EXPOSE 9000

# Lệnh chạy API bằng uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "9000"]
